###
GET http://localhost:3000/questions
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InpKbmFZQVRaX2czYTdRUjhJV1pEOSJ9.eyJpc3MiOiJodHRwczovL2Rldi1kNHRmNG0xbWc0NzBtbjRzLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJHY1ZjT05uTjl4YmpuNWk5Y0pJcFNYVnlRd0JVWm5hRUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9mY3QtYXBpLmNvbSIsImlhdCI6MTcwOTQ3MDgwMywiZXhwIjoxNzA5NTU3MjAzLCJhenAiOiJHY1ZjT05uTjl4YmpuNWk5Y0pJcFNYVnlRd0JVWm5hRSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsInBlcm1pc3Npb25zIjpbXX0.lSOnVysZGVbjwdJYpeyxE36oVhQoKT1JjXefqBgaQeEckinnTlwHB3m5vB4Y4K9rl2cnoh8rx_fZS2we4tkH5rMWSohMSWyXn6qGBJj6xG3V7AtFZvizwiCQIm7LSn_eMRTIEtU4hNaW96veftH43uQCmm20tW7F85W7iaC4IoBmpWS2ObvYwd9ZhhM_6fM8R78M_4kT-x_4g6QIh-5GvizOedbJbPsanGhRJSgGOLW0lWxBek4H48IDsvvFd3aIF30g18_5HDMnArFJlB-QJaqmdSUHhFJmNXIW9p97KIs9o4D2917sjzvtkBC0TWo7-jtlSTU9nWs9GsAOc5yc_A

###
POST http://localhost:3000/questions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InpKbmFZQVRaX2czYTdRUjhJV1pEOSJ9.eyJpc3MiOiJodHRwczovL2Rldi1kNHRmNG0xbWc0NzBtbjRzLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJHY1ZjT05uTjl4YmpuNWk5Y0pJcFNYVnlRd0JVWm5hRUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9mY3QtYXBpLmNvbSIsImlhdCI6MTcwOTQ3MDgwMywiZXhwIjoxNzA5NTU3MjAzLCJhenAiOiJHY1ZjT05uTjl4YmpuNWk5Y0pJcFNYVnlRd0JVWm5hRSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsInBlcm1pc3Npb25zIjpbXX0.lSOnVysZGVbjwdJYpeyxE36oVhQoKT1JjXefqBgaQeEckinnTlwHB3m5vB4Y4K9rl2cnoh8rx_fZS2we4tkH5rMWSohMSWyXn6qGBJj6xG3V7AtFZvizwiCQIm7LSn_eMRTIEtU4hNaW96veftH43uQCmm20tW7F85W7iaC4IoBmpWS2ObvYwd9ZhhM_6fM8R78M_4kT-x_4g6QIh-5GvizOedbJbPsanGhRJSgGOLW0lWxBek4H48IDsvvFd3aIF30g18_5HDMnArFJlB-QJaqmdSUHhFJmNXIW9p97KIs9o4D2917sjzvtkBC0TWo7-jtlSTU9nWs9GsAOc5yc_A

{
  "id": "123"
}